apiVersion: v1
kind: Service
metadata:
  name: prefer-nodelocal
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
#  topologyKeys:
#    - "kubernetes.io/hostname"
#    - "topology.kubernetes.io/zone"
#    - "topology.kubernetes.io/region"
#    - "*"