apiVersion: v1
kind: Pod
metadata:
  name: http-3-pod-probe
spec:
  containers:
    - name: http-3-pod-probe
      image: nginx
      readinessProbe:
        httpGet:
          ### this 3-pod-probe will fail with 404 error code
          ### only httpcode between 200-400 is retreated as success
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 2